on:
  push:
    branches:
    - main
    - release/*
on:
  pull_request:
  runs on: windows-latest
    print: echo 'OK'
    
on:
  schedule:
  - cron: "0 2 * * 1-5"
- name: Setup Node
  uses: actions/setup-node@v1
  with:
    node-version: '10.x'
